### ISSUE TITLE
Set features not used in config file

### ISSUE THREAD

**Issue by anusharanganathan** [anusharanganathan/dataPaperCompanion#39]
Currently after registering a user and assigning admin rights to the user, the user need to log-in and turn off the following features in order for the form to work 
1. Show deposit agreement
2. Active deposit agreement acceptance

I have also turned off these features as it isn't used
1. Assign admin set
2. Batch upload

**Comment by martyn-w** [comment]
Hi @anusharanganathan, I've added a new rake task which can be used to set these features before startup with a rake command:

```
rake features:set["show_deposit_agreement:false","active_deposit_agreement_acceptance:false","assign_admin_set:false","batch_upload:false"]
```
